### ISSUE TITLE
💻- Leveraging other API's to find what others' are listening to

### ISSUE THREAD

**Issue by sauconny** [shmam/sam-as-a-service#1]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8af413ed-694d-413f-93d2-aee2038b1249-6d1743ed-9aa2-4302-84f0-21b0b87c9105-v1.png?transparent=1&palette=1&width=246)

## Issue 
I assume we would need everyone's credentials in order to find out what they're listening to, right? So basically displaying a list of your friends (via Snapchat, Facebook, Instagram) and what they're listening to. 

Feel free to close the issue if it is not possible.

**Comment by shmam** [comment]
I like the idea alot! Unfortunately the only (as far as I know I wish there were others) public facing API endpoint for getting currently playing tracks is [api.spotify.com/v1/me/player](https://developer.spotify.com/console/get-user-player/), which only gets the info for me :(. This endpoint also requires a more complex [Authorization Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) to use which took a [sketchy workaround](https://spotipy.readthedocs.io/en/latest/#authorization-code-flow) to make this run on an EC2 instance. 

With all of this being said. If the app was expanded so multiple users could grant their own authorization and have their own service to fetch their currently playing tracks to feed into a central service, that would be really cool.

**Comment by sauconny** [comment]
Definitely looks complex, just as I assumed. I will go ahead and close the issue. Great work on this sir 😊
